
package gui;

import model.Kerdes;

public class KerdesAdatok extends javax.swing.JDialog {

    private Kerdes kerdes; //A listából kiválasztott kérdés
    private boolean mentes; //A mentés gomb által beállított változó
    
    public KerdesAdatok(java.awt.Frame parent, boolean modal, Kerdes kerdes) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        this.kerdes = kerdes;
        this.mentes = false;
        
        if (kerdes == null) {
            setTitle("Új kérdés");
        } else {
            setTitle("Kérdés szerkesztése");
            tfKerdes.setText(kerdes.getKerdes());  //A kérdés és a válaszok megjelenítése
            tfValasz0.setText(kerdes.getValasz0());
            tfValasz1.setText(kerdes.getValasz1());
            tfValasz2.setText(kerdes.getValasz2());
            tfValasz3.setText(kerdes.getValasz3());
            
            int helyesValasz = kerdes.getHelyesValasz(); //A helyes válasz megjelenítése rádiógombokkal
            switch (helyesValasz) {
                case 0 : rbHelyes0.setSelected(true);
                break;
                case 1 : rbHelyes1.setSelected(true);
                break;
                case 2 : rbHelyes2.setSelected(true);
                break;
                case 3 : rbHelyes3.setSelected(true);
            }
        }        
    }

    public Kerdes getKerdes() { //A getter adja vissza a kérdést a listának
        return kerdes;
    }

    public boolean isMentes() {
        return mentes;
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfKerdes = new javax.swing.JTextField();
        tfValasz0 = new javax.swing.JTextField();
        tfValasz1 = new javax.swing.JTextField();
        tfValasz2 = new javax.swing.JTextField();
        tfValasz3 = new javax.swing.JTextField();
        rbHelyes0 = new javax.swing.JRadioButton();
        rbHelyes1 = new javax.swing.JRadioButton();
        rbHelyes2 = new javax.swing.JRadioButton();
        rbHelyes3 = new javax.swing.JRadioButton();
        btnMegsem = new javax.swing.JButton();
        btnMentes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Kérdés");

        jLabel1.setText("Kérdés");

        jLabel2.setText("A válasz");

        jLabel3.setText("B válasz");

        jLabel4.setText("C válasz");

        jLabel5.setText("D válasz");

        jLabel6.setText("Helyes válasz");

        tfKerdes.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        tfValasz0.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        tfValasz1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        tfValasz2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        tfValasz3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        buttonGroup1.add(rbHelyes0);
        rbHelyes0.setText("A");
        rbHelyes0.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        buttonGroup1.add(rbHelyes1);
        rbHelyes1.setText("B");
        rbHelyes1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        buttonGroup1.add(rbHelyes2);
        rbHelyes2.setText("C");
        rbHelyes2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        buttonGroup1.add(rbHelyes3);
        rbHelyes3.setText("D");
        rbHelyes3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        btnMegsem.setText("Mégsem");
        btnMegsem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMegsemActionPerformed(evt);
            }
        });

        btnMentes.setText("Mentés");
        btnMentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMentesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(rbHelyes0)
                        .addGap(18, 18, 18)
                        .addComponent(rbHelyes1)
                        .addGap(18, 18, 18)
                        .addComponent(rbHelyes2)
                        .addGap(18, 18, 18)
                        .addComponent(rbHelyes3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                        .addComponent(btnMentes)
                        .addGap(18, 18, 18)
                        .addComponent(btnMegsem))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(25, 25, 25)
                        .addComponent(tfKerdes))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(tfValasz0))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(19, 19, 19)
                        .addComponent(tfValasz1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(tfValasz2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(tfValasz3)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnMegsem, btnMentes});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfKerdes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfValasz0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfValasz1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfValasz2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfValasz3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(rbHelyes0)
                    .addComponent(rbHelyes1)
                    .addComponent(rbHelyes2)
                    .addComponent(rbHelyes3)
                    .addComponent(btnMegsem)
                    .addComponent(btnMentes))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMegsemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMegsemActionPerformed
        setVisible(false); //Az ablak bezárása mentés nélkül.
    }//GEN-LAST:event_btnMegsemActionPerformed

    /*
    * A mentés gomb hatására a változások vagy újonnan beírt adatok mentésre kerülnek. 
    */
    private void btnMentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMentesActionPerformed
        mentes = true;
        if (kerdes == null) {
            kerdes = new Kerdes(); //Új kérdés létrehozása
            
        }
        kerdes.setKerdes(tfKerdes.getText());  //A kérdés objektum adattagjainak beállítása a megjelenített kérdés és válaszok alapján  
        kerdes.setValasz0(tfValasz0.getText());
        kerdes.setValasz1(tfValasz1.getText());
        kerdes.setValasz2(tfValasz2.getText());
        kerdes.setValasz3(tfValasz3.getText());
        
        int helyesValasz; //A helyes választ tartalmazó változó értékének beállítása.
        if (rbHelyes0.isSelected()) {
            helyesValasz = 0;
        } else if (rbHelyes1.isSelected()) {
            helyesValasz = 1;
        } else if (rbHelyes2.isSelected()) {
            helyesValasz = 2;
        } else {
            helyesValasz = 3;
        }
        kerdes.setHelyesValasz(helyesValasz);
        
        setVisible(false); //Az ablak bezárása.
    }//GEN-LAST:event_btnMentesActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMegsem;
    private javax.swing.JButton btnMentes;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton rbHelyes0;
    private javax.swing.JRadioButton rbHelyes1;
    private javax.swing.JRadioButton rbHelyes2;
    private javax.swing.JRadioButton rbHelyes3;
    private javax.swing.JTextField tfKerdes;
    private javax.swing.JTextField tfValasz0;
    private javax.swing.JTextField tfValasz1;
    private javax.swing.JTextField tfValasz2;
    private javax.swing.JTextField tfValasz3;
    // End of variables declaration//GEN-END:variables
}
